In [2]:
%pip install pandas
%pip install numpy

Requirement already satisfied: pandas in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (2.3.1)
Note: you may need to restart the kernel to use updated packages.

### Collecting data & Preprocessing

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("sdss_100k_galaxy_form_burst.csv")

In [5]:
df

,objid,specobjid,ra,dec,u,g,r,i,z,modelFlux_u,...,psfMag_z,expAB_u,expAB_g,expAB_r,expAB_i,expAB_z,class,subclass,redshift,redshift_err
0,1237646587710669400,8175185722644649984,82.038679,0.847177,21.73818,20.26633,19.32409,18.64037,18.23833,2.007378,...,19.43575,0.099951,0.311864,0.289370,0.270588,0.187182,GALAXY,STARFORMING,0.067749,0.000015
1,1237646588247540577,8175186822156277760,82.138894,1.063072,20.66761,19.32016,18.67888,18.24693,18.04122,5.403369,...,18.85012,0.366549,0.516876,0.517447,0.552297,0.636966,GALAXY,STARFORMING,0.105118,0.000010
2,1237646588247540758,8175187097034184704,82.028510,1.104003,23.63531,21.19671,19.92297,19.31443,18.68396,0.295693,...,19.42235,0.050000,0.417137,0.506950,0.549881,0.370166,GALAXY,STARFORMING,0.234089,0.000030
3,1237648702973083853,332152325571373056,198.544469,-1.097059,20.12374,18.41520,17.47202,17.05297,16.72423,8.920645,...,18.03204,0.310763,0.356827,0.389345,0.388160,0.416660,GALAXY,STARFORMING,0.110825,0.000030
4,1237648702973149350,332154249716721664,198.706864,-1.046217,-9999.00000,-9999.00000,18.37762,18.13383,17.78497,0.000000,...,19.02880,-9999.000000,-9999.000000,0.050000,0.050000,0.149973,GALAXY,STARFORMING,0.136658,0.000021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1237667782852804885,3130040850139080704,228.558321,16.759520,20.09288,18.25375,17.28985,16.82903,16.43054,9.177956,...,17.91477,0.283251,0.308447,0.318548,0.313944,0.361409,GALAXY,STARFORMING,0.116555,0.000022
99996,1237667783343867090,5077945562323769344,119.601880,10.351615,22.09939,20.82547,19.02462,18.43225,17.96795,1.432706,...,19.48296,0.050000,0.705830,0.772447,0.738316,0.611691,GALAXY,STARFORMING,0.366410,0.000093
99997,1237667783392755908,2834003941597931520,235.609200,15.242749,19.31622,18.14944,17.45517,17.04435,16.77127,18.770960,...,18.74449,0.406675,0.363766,0.367104,0.373286,0.389484,GALAXY,STARFORMING,0.127064,0.000010
99998,1237667783392821500,2834003391842117632,235.789986,15.189821,19.03856,18.17619,17.53119,17.05532,16.85166,24.241610,...,17.75661,0.937029,0.930673,0.884711,0.859936,0.873763,GALAXY,STARFORMING,0.116330,0.000011
99999,1237667783922549049,6641903828970264576,219.376185,19.766648,20.63641,20.12450,19.96307,19.35898,19.51870,5.561124,...,20.38782,0.053815,0.304459,0.241673,0.258522,0.364446,GALAXY,STARBURST,0.100121,0.000007

In [6]:
df.head()

,objid,specobjid,ra,dec,u,g,r,i,z,modelFlux_u,...,psfMag_z,expAB_u,expAB_g,expAB_r,expAB_i,expAB_z,class,subclass,redshift,redshift_err
0,1237646587710669400,8175185722644649984,82.038679,0.847177,21.73818,20.26633,19.32409,18.64037,18.23833,2.007378,...,19.43575,0.099951,0.311864,0.289370,0.270588,0.187182,GALAXY,STARFORMING,0.067749,0.000015
1,1237646588247540577,8175186822156277760,82.138894,1.063072,20.66761,19.32016,18.67888,18.24693,18.04122,5.403369,...,18.85012,0.366549,0.516876,0.517447,0.552297,0.636966,GALAXY,STARFORMING,0.105118,0.000010
2,1237646588247540758,8175187097034184704,82.028510,1.104003,23.63531,21.19671,19.92297,19.31443,18.68396,0.295693,...,19.42235,0.050000,0.417137,0.506950,0.549881,0.370166,GALAXY,STARFORMING,0.234089,0.000030
3,1237648702973083853,332152325571373056,198.544469,-1.097059,20.12374,18.41520,17.47202,17.05297,16.72423,8.920645,...,18.03204,0.310763,0.356827,0.389345,0.388160,0.416660,GALAXY,STARFORMING,0.110825,0.000030
4,1237648702973149350,332154249716721664,198.706864,-1.046217,-9999.00000,-9999.00000,18.37762,18.13383,17.78497,0.000000,...,19.02880,-9999.000000,-9999.000000,0.050000,0.050000,0.149973,GALAXY,STARFORMING,0.136658,0.000021

In [7]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 43 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   objid         100000 non-null  int64
 1   specobjid     100000 non-null  uint64
 2   ra            100000 non-null  float64
 3   dec           100000 non-null  float64
 4   u             100000 non-null  float64
 5   g             100000 non-null  float64
 6   r             100000 non-null  float64
 7   i             100000 non-null  float64
 8   z             100000 non-null  float64
 9   modelFlux_u   100000 non-null  float64
 10  modelFlux_g   100000 non-null  float64
 11  modelFlux_r   100000 non-null  float64
 12  modelFlux_i   100000 non-null  float64
 13  modelFlux_z   100000 non-null  float64
 14  petroRad_u    100000 non-null  float64
 15  petroRad_g    100000 non-null  float64
 16  petroRad_i    100000 non-null  float64
 17  petroRad_r    100000 non-null  float64
 18  petroRad_z    100000 non-null  float64
 19  petroFlux_u   100000 non-null  float64
 20  petroFlux_g   100000 non-null  float64
 21  petroFlux_i   100000 non-null  float64
 22  petroFlux_r   100000 non-null  float64
 23  petroFlux_z   100000 non-null  float64
 24  petroR50_u    100000 non-null  float64
 25  petroR50_g    100000 non-null  float64
 26  petroR50_i    100000 non-null  float64
 27  petroR50_r    100000 non-null  float64
 28  petroR50_z    100000 non-null  float64
 29  psfMag_u      100000 non-null  float64
 30  psfMag_r      100000 non-null  float64
 31  psfMag_g      100000 non-null  float64
 32  psfMag_i      100000 non-null  float64
 33  psfMag_z      100000 non-null  float64
 34  expAB_u       100000 non-null  float64
 35  expAB_g       100000 non-null  float64
 36  expAB_r       100000 non-null  float64
 37  expAB_i       100000 non-null  float64
 38  expAB_z       100000 non-null  float64
 39  class         100000 non-null  object
 40  subclass      100000 non-null  object
 41  redshift      100000 non-null  float64
 42  redshift_err  100000 non-null  float64
dtypes: float64(39), int64(1), object(2), uint64(1)
memory usage: 32.8+ MB

,objid,specobjid,ra,dec,u,g,r,i,z,modelFlux_u,...,psfMag_g,psfMag_i,psfMag_z,expAB_u,expAB_g,expAB_r,expAB_i,expAB_z,redshift,redshift_err
count,1.000000e+05,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,1.237659e+18,2.303595e+18,180.577802,23.472475,18.518622,17.258221,16.821739,16.362611,15.850865,30.683321,...,18.834259,18.020203,17.435735,-0.603667,-0.522111,-0.309462,-0.410153,-0.740964,0.116753,0.000179
std,6.103756e+12,2.531359e+18,75.751994,21.140744,105.082004,105.069066,95.035474,100.171155,114.206165,76.552859,...,105.079620,100.181687,114.218604,104.870665,104.871474,94.860919,99.991654,114.005927,0.100169,0.052189
min,1.237646e+18,2.994897e+17,0.008745,-11.244273,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-47.451720,...,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-0.000833,0.000002
25%,1.237655e+18,8.130687e+17,138.741880,3.120118,18.762215,17.505868,16.898845,16.527097,16.281327,9.288132,...,19.257783,18.295627,17.991602,0.299999,0.398705,0.418789,0.418656,0.381288,0.055836,0.000008
50%,1.237659e+18,1.457564e+18,181.492972,20.913596,19.349715,18.072640,17.459080,17.091385,16.861105,18.195690,...,19.763915,18.845780,18.563315,0.508688,0.588335,0.604795,0.604254,0.575397,0.085850,0.000011
75%,1.237663e+18,2.367902e+18,223.851863,42.259965,20.079470,18.656182,17.926918,17.592650,17.453848,31.259628,...,20.408775,19.586577,19.299430,0.699907,0.768804,0.773924,0.773119,0.752311,0.135148,0.000015
max,1.237681e+18,1.412691e+19,359.997922,68.695258,30.960000,30.420980,31.173560,30.562360,28.553240,7915.306000,...,26.174400,25.966680,27.043280,1.000000,1.000000,0.999999,1.000000,0.999998,0.572899,16.503710

## Checking empty cells

In [8]:

empty_columns = df.columns[df.isna().all()].tolist()
print("Empty columns:", empty_columns)

Empty columns: []

In [9]:
df.head()

,objid,specobjid,ra,dec,u,g,r,i,z,modelFlux_u,...,psfMag_z,expAB_u,expAB_g,expAB_r,expAB_i,expAB_z,class,subclass,redshift,redshift_err
0,1237646587710669400,8175185722644649984,82.038679,0.847177,21.73818,20.26633,19.32409,18.64037,18.23833,2.007378,...,19.43575,0.099951,0.311864,0.289370,0.270588,0.187182,GALAXY,STARFORMING,0.067749,0.000015
1,1237646588247540577,8175186822156277760,82.138894,1.063072,20.66761,19.32016,18.67888,18.24693,18.04122,5.403369,...,18.85012,0.366549,0.516876,0.517447,0.552297,0.636966,GALAXY,STARFORMING,0.105118,0.000010
2,1237646588247540758,8175187097034184704,82.028510,1.104003,23.63531,21.19671,19.92297,19.31443,18.68396,0.295693,...,19.42235,0.050000,0.417137,0.506950,0.549881,0.370166,GALAXY,STARFORMING,0.234089,0.000030
3,1237648702973083853,332152325571373056,198.544469,-1.097059,20.12374,18.41520,17.47202,17.05297,16.72423,8.920645,...,18.03204,0.310763,0.356827,0.389345,0.388160,0.416660,GALAXY,STARFORMING,0.110825,0.000030
4,1237648702973149350,332154249716721664,198.706864,-1.046217,-9999.00000,-9999.00000,18.37762,18.13383,17.78497,0.000000,...,19.02880,-9999.000000,-9999.000000,0.050000,0.050000,0.149973,GALAXY,STARFORMING,0.136658,0.000021

## Training & Spliting

In [15]:
y = df['redshift']

In [16]:
import pandas as pd

df = pd.read_csv('sdss_100k_galaxy_form_burst.csv')

# Example: regression on redshift
y = df['redshift']

# drop everything that isn’t a numeric input feature
X_all = df.drop(columns=[
    'objid', 'specobjid',      # identifiers
    'class', 'subclass',       # if you’re not using them as targets
    'redshift', 'redshift_err' # if you’re predicting redshift
])

# now split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_all, y, test_size=0.2, random_state=42
)

## Tranining Model

In [17]:
import pandas as pd

df = pd.read_csv('sdss_100k_galaxy_form_burst.csv')

# Example: regression on redshift
y = df['redshift']

# drop everything that isn’t a numeric input feature
X_all = df.drop(columns=[
    'objid', 'specobjid',      # identifiers
    'class', 'subclass',       # if you’re not using them as targets
    'redshift', 'redshift_err' # if you’re predicting redshift
])

# now split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_all, y, test_size=0.2, random_state=42
)

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error

# 1. Load data
df = pd.read_csv('sdss_100k_galaxy_form_burst.csv')

# 2. Define target and features
y = df['redshift']
X_all = df.drop(columns=[
    'objid', 'specobjid',
    'class', 'subclass',
    'redshift', 'redshift_err'
])

# 3. Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X_all, y,
    test_size=0.2,
    random_state=42
)

# 4. Instantiate & fit model
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
model.fit(X_train, y_train)

# 5. Evaluate
y_pred = model.predict(X_test)
r2  = r2_score(y_test, y_pred)


from sklearn.metrics import mean_squared_error, r2_score

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"Test R²   : {r2:.3f}")
print(f"Test RMSE : {rmse:.3f}")

Test R²   : 0.834
Test RMSE : 0.041

In [21]:
%pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (1.7.0)
Requirement already satisfied: numpy>=1.22.0 in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (from scikit-learn) (2.3.1)
Requirement already satisfied: scipy>=1.8.0 in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (from scikit-learn) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\pranj\desktop\final project (ssds)\.venv\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error
import joblib

# 1. Load data
df = pd.read_csv('sdss_100k_galaxy_form_burst.csv')

# 2. Define target and features
y = df['redshift']
X = df.drop(columns=[
    'objid', 'specobjid',
    'class', 'subclass',
    'redshift', 'redshift_err'
])

# 3. Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# 4. Train model
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
model.fit(X_train, y_train)

# 5. Predict & evaluate
y_pred = model.predict(X_test)

# Using sklearn’s built‑in RMSE (if supported)
try:
    rmse = mean_squared_error(y_test, y_pred, squared=False)
except TypeError:
    # fallback for older sklearn
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"Test R²   : {r2_score(y_test, y_pred):.3f}")
print(f"Test RMSE : {rmse:.3f}")

# 6. Save model
joblib.dump(model, 'rf_redshift_model.pkl')
print("Model saved to rf_redshift_model.pkl")

Test R²   : 0.834
Test RMSE : 0.041
Model saved to rf_redshift_model.pkl

In [25]:
import pandas as pd
import joblib
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

# 1. Load your saved model
model = joblib.load('model.pkl')

# 2. Reload your data (or load a separate test set)
df = pd.read_csv('sdss_100k_galaxy_form_burst.csv')

# 3. Recreate X and y exactly as in training
y = df['redshift']
X = df.drop(columns=[
    'objid', 'specobjid',
    'class', 'subclass',
    'redshift', 'redshift_err'
])

# 4. If you want to re‑use the same test split:
from sklearn.model_selection import train_test_split
_, X_test, _, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 5. Make predictions
y_pred = model.predict(X_test)

# 6. Evaluate
r2   = r2_score(y_test, y_pred)
mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"Test R²   : {r2:.3f}")
print(f"Test RMSE : {rmse:.3f}")

# 7. (Optional) Predict on new data samples:
# new_data should be a DataFrame or 2D array with the same feature columns as X
# Example:
# new_data = pd.DataFrame([{
#     'ra': 192.75, 'dec': 27.41, 'u': 17.2, 'g': 16.8, … 
# }])
# preds = model.predict(new_data)
# print("Predicted redshift:", preds)

Test R²   : 0.834
Test RMSE : 0.041